events { worker_connections 1024; }

http {
    server {
        listen 80;
        server_name blog.cmh.sh blog4.cmh.sh cmh.sh ots.cmh.sh
                    colinhayes.dev blog.colinhayes.dev about.colinhayes.dev links.colinhayes.dev;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 'provisioning';
            add_header Content-Type text/plain;
        }
    }
}